In [1]:
import pandas as pd
import numpy as np

In [2]:
cd

/Users/raghavraahul


In [3]:
cd Downloads/NLP

/Users/raghavraahul/Downloads/NLP


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("spam.csv", encoding = "ISO-8859-1") #encoding
#https://stackoverflow.com/questions/18171739/unicodedecodeerror-when-reading-csv-file-in-pandas

In [6]:
df = df[['Category', 'Message']]

In [7]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
def get_spam(x):
    if x == 'spam':
        return 1
    return 0

#two ways of doing the same thing
df['spam'] = df.Category.apply(lambda x: 1 if x == 'spam' else 0)
#df['spam'] = df.Category.apply(get_spam)

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [12]:
X_train.shape

(4457,)

In [13]:
X_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[:4]

5132    it's still not working. And this time i also t...
3071                               Ok lor... But buy wat?
1535    You have won a Nokia 7250i. This is what you g...
5385    How do friends help us in problems? They give ...
Name: Message, dtype: object

In [16]:
type(y_train)

pandas.core.series.Series

In [17]:
y_train[:4]

5132    0
3071    0
1535    1
5385    0
Name: spam, dtype: int64

In [18]:
#count vectorizer to build bag of model for our numeric representation
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values) #.values has to be used because .values is needed to convert series object to numpy array
X_train_cv

<4457x7731 sparse matrix of type '<class 'numpy.int64'>'
	with 59059 stored elements in Compressed Sparse Row format>

In [19]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
X_train_cv.shape

(4457, 7731)

In [21]:
type(v)

sklearn.feature_extraction.text.CountVectorizer

In [22]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [23]:
v.vocabulary_

{'it': 3754,
 'still': 6438,
 'not': 4819,
 'working': 7566,
 'and': 962,
 'this': 6812,
 'time': 6858,
 'also': 931,
 'tried': 6991,
 'adding': 816,
 'zeros': 7709,
 'that': 6768,
 'was': 7352,
 'the': 6774,
 'savings': 5885,
 'checking': 1760,
 'is': 3742,
 'lt': 4246,
 'gt': 3256,
 'ok': 4901,
 'lor': 4204,
 'but': 1576,
 'buy': 1581,
 'wat': 7360,
 'you': 7676,
 'have': 3346,
 'won': 7547,
 'nokia': 4795,
 '7250i': 613,
 'what': 7442,
 'get': 3114,
 'when': 7448,
 'win': 7491,
 'our': 4991,
 'free': 2981,
 'auction': 1143,
 'to': 6888,
 'take': 6644,
 'part': 5067,
 'send': 5971,
 '86021': 687,
 'now': 4833,
 'hg': 3413,
 'suite342': 6543,
 '2lands': 398,
 'row': 5797,
 'w1jhl': 7296,
 '16': 313,
 'how': 3517,
 'do': 2366,
 'friends': 3000,
 'help': 3389,
 'us': 7168,
 'in': 3632,
 'problems': 5403,
 'they': 6797,
 'give': 3141,
 'most': 4585,
 'stupid': 6499,
 'suggestion': 6541,
 'lands': 4003,
 'into': 3709,
 'another': 982,
 'problem': 5401,
 'helps': 3394,
 'forgt': 2952,
 'pr

In [35]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
np.where(X_train_np[0] != 0)

(array([ 816,  931,  962, 1760, 3256, 3742, 3754, 4246, 4819, 5885, 6438,
        6768, 6774, 6812, 6858, 6991, 7352, 7566, 7709]),)

In [38]:
X_train_np[0][816]

1

In [41]:
X_train_np[0][930]

0

In [42]:
X_train_np[0][6858]

1

In [45]:
v.get_feature_names_out()[816]

'adding'

In [46]:
#import naive bayes classifier

#there are two types of NB classifier
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

#evaluate performance of model
X_test_cv = v.transform(X_test.values)

In [48]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)

In [50]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       976
           1       0.99      0.89      0.94       139

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [52]:
#f1 score is a good metric to use because the training data set is imbalanced without 4800 ham and 750 spam

In [53]:
#implement count vectorizer bag of words using sklearn pipeline

from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb', MultinomialNB())
])

In [54]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [55]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       976
           1       0.99      0.89      0.94       139

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115

